stages:
  - Pre-Build
  - Build & Publish

variables:
  REPO_NAME: us-east1-docker.pkg.dev/what-am-i-listening-to-357216/what-am-i-listening-to
  IMAGE_NAME: whatamilisteningto

Lint:
  stage: Pre-Build
  image: node:latest
  script:
    - npm ci
    - npm run lint
  except:
    - tags

Build & Publish:
  stage: Build & Publish
  services:
    - docker:dind
  image: docker:latest
  script:
    - docker login -u _json_key --password-stdin https://us-east1-docker.pkg.dev < $GCLOUD_SERVICE_KEY_JSON
    - docker build . -t "$REPO_NAME/$IMAGE_NAME:$CI_COMMIT_TAG" -t "$REPO_NAME/$IMAGE_NAME:latest"
    - docker push "$REPO_NAME/$IMAGE_NAME:$CI_COMMIT_TAG" 
    - docker push "$REPO_NAME/$IMAGE_NAME:latest"
  only:
    - tags


