stages:
  - Pre-Build
  - Build & Publish

variables:
  IMAGE_NAME: what-am-i-listening-to

Lint:
  stage: Pre-Build
  image: node:latest
  script:
    - npm ci
    - npm run lint

Build Docker Image:
  stage: Build
  services:
    - docker:dind
  image: docker:latest
  script:
    - docker build . -t $IMAGE_NAME:latest -o type=local,path=out
  artifacts:
    paths:
      - out/

Publish Docker Image:
  stage: Build
  services:
    - docker:dind
  image: google/cloud-sdk:latest
  script:
    - gcloud auth activate-service-account
  needs:
    - Build Docker Image


