stages:
  - Pre-Build
  - Build & Publish
  - Release

variables:
  REPO_LOCATION: us-east1-docker.pkg.dev/what-am-i-listening-to-1104/whatsvincentlisteningto-repo1 # full path to the in artifact registry, i.e., us-east1-docker.pkg.dev/what-am-i-listening-to-357216/what-am-i-listening-to
  IMAGE_NAME: whatamilisteningto # name of the docker image in artifact registry, i.e., whatamilisteningto
  SERVICE_NAME: test-service # name of the service in cloud run, i.e., whatsreidlisteningto
  PROJECT_ID: what-am-i-listening-to-1104 # id of the project used, i.e., what-am-i-listening-to-357216
  REGION: us-east1 # i.e., us-east1

Lint:
  stage: Pre-Build
  image: node:latest
  script:
    - npm ci
    - npm run lint
  except:
    - tags

Build & Publish:
  stage: Build & Publish
  services:
    - docker:dind
  image: docker:latest
  script:
    - docker login -u _json_key --password-stdin https://$REGION-docker.pkg.dev < $GCLOUD_SERVICE_KEY_JSON
    - docker build . -t "$REPO_LOCATION/$IMAGE_NAME:$CI_COMMIT_TAG" -t "$REPO_LOCATION/$IMAGE_NAME:latest"
    - docker push "$REPO_LOCATION/$IMAGE_NAME:$CI_COMMIT_TAG" 
    - docker push "$REPO_LOCATION/$IMAGE_NAME:latest"
  only:
    - tags
  
Deploy to Google Cloud Run:
    stage: Release
    image: google/cloud-sdk:latest
    only:
        - tags
    when: manual
    script:
      - gcloud auth activate-service-account --key-file $GCLOUD_SERVICE_KEY_JSON
      - gcloud run deploy --image "$REPO_LOCATION/$IMAGE_NAME:latest" --project $PROJECT_ID --platform managed --region $REGION



