stages:
  - Pre-Build
  - Build & Publish

variables:
  IMAGE_NAME: us-east1-docker.pkg.dev/what-am-i-listening-to-357216/what-am-i-listening-to

Lint:
  stage: Pre-Build
  image: node:latest
  script:
    - npm ci
    - npm run lint
  except:
    - tags

Build & Publish:
  stage: Build & Publish
  services:
    - docker:dind
  image: docker:latest
  script:
    - echo $GCLOUD_SERVICE_KEY_JSON > ${HOME}/gcloud-service-key.json
    - docker login -u _json_key -p "$(cat ${HOME}/gcloud-service-key.json)" https://us-east1-docker.pkg.dev
    - docker build . -t "$IMAGE_NAME:$CI_COMMIT_TAG" -t "$IMAGE_NAME:latest"
    - docker push "$IMAGE_NAME:$CI_COMMIT_TAG" 
    - docker push "$IMAGE_NAME:latest"
  only:
    - tags


