stages:
  - Pre-Build
  - Build & Publish

variables:
  IMAGE_NAME: "us-east1-docker.pkg.dev/what-am-i-listening-to-357216/what-am-i-listening-to:latest"

Lint:
  stage: Pre-Build
  image: node:latest
  script:
    - npm ci
    - npm run lint

Build & Publish:
  stage: Build
  services:
    - docker:dind
  image: docker:latest
  script:
    - echo $GCLOUD_SERVICE_KEY_JSON > ${HOME}/gcloud-service-key.json
    - docker login -u _json_key --password-stdin https://us-east1-docker.pkg.dev < ${HOME}/gcloud-service-key.json
    - docker build . -t $IMAGE_NAME
    - docker push $IMAGE_NAME
  only:
    - main


